# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-10 08:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_auto_20170210_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='insertion_date',
            field=models.DateField(default=datetime.datetime(2017, 2, 7, 10, 37, 21, 39812)),
        ),
    ]
